sonar.projectKey=cloudaura_frontend
sonar.projectName=Cloudaura Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/yallatn/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
