package org.example.backend.dto.transport;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class EngineRecommendationResponse {

    /** Best scored option (null if nothing available). */
    private TransportOption bestOption;

    /** Up to 3 alternative available options (sorted by score). */
    private List<TransportOption> alternatives;

    /** All generated options including unavailable (for comparison table). */
    private List<TransportOption> allOptions;

    /** Human-readable explanation of why this option is recommended. */
    private String recommendationReason;

    /** Optional multi-modal combination tip. */
    private String combinationSuggestion;

    private int    distanceKm;
    private String fromCity;
    private String toCity;
    private int    passengers;

    // ─────────────────────────────────────────────────────────────────────────
    @Data @Builder @NoArgsConstructor @AllArgsConstructor
    public static class TransportOption {

        /** DB transport_id – null for virtual (computed) options. */
        private Integer transportId;

        /** Display label, e.g. "Bus SNTRI", "Louage (Taxi Collectif)". */
        private String type;

        /** Raw enum name, e.g. "BUS", "VAN", "TAXI", "PLANE", "CAR". */
        private String rawType;

        // ── STEP 2: Dynamically computed values (not read from DB) ─────────

        /** Total price for all passengers (TND). */
        private double price;

        /** Price per individual passenger (TND). */
        private double pricePerPerson;

        /** Formatted price string, e.g. "14.50 TND". */
        private String priceFormatted;

        /** Human-readable duration, e.g. "2h30". */
        private String duration;

        /** Duration in minutes. */
        private int durationMinutes;

        /** Computed departure time (HH:mm). From DB for real transports; default for virtual. */
        private String departureTime;

        /** Computed arrival time = departure + duration (HH:mm). */
        private String arrivalTime;

        // ── STEP 1: Seats left = capacity – SUM(reservations) ─────────────
        private int seatsLeft;

        /** True if option is available AND has enough seats. */
        private boolean available;

        /** Reason for unavailability (e.g. "Pas d'aéroport à Médenine"). */
        private String availabilityInfo;

        /** True if this option was generated by formula (not a real DB row). */
        private boolean virtual;

        private String       description;
        private List<String> features;

        /** Raw score (lower = better). Used internally for sorting. */
        private double score;

        /** AI score 0–100 (higher = better) – displayed to the user. */
        private int aiScore;
    }
}
